// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosregistry/example/v1/types.proto

package example

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d1cf6348eb2ada, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Metadata defines the middleware specific metadata encoded into the channel
// version bytestring See ICS004:
// https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#Versioning
// If the middleware is a stateless middleware, you need not include any
// metadata, and can omit this message.
type Metadata struct {
	// middleware_version defines the middleware version
	MiddlewareVersion string `protobuf:"bytes,1,opt,name=middleware_version,json=middlewareVersion,proto3" json:"middleware_version,omitempty"`
	// app_version defines the underlying application version, which may or may
	// not be a JSON encoded bytestring
	AppVersion string `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d1cf6348eb2ada, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMiddlewareVersion() string {
	if m != nil {
		return m.MiddlewareVersion
	}
	return ""
}

func (m *Metadata) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

// Counter defines a counter object.
// It is used only for genesis purposes. Collections does not need to use it.
type CallbackCounter struct {
	// on_chan_open counts the number of times OnChanOpenAck or OnChanOpenConfirm
	// is called in the underlying channel.
	OnChanOpen uint64 `protobuf:"varint,1,opt,name=on_chan_open,json=onChanOpen,proto3" json:"on_chan_open,omitempty"`
	// on_recv_packet counts the number of times OnRecvPacket is called in the
	// underlying channel.
	OnRecvPacket uint64 `protobuf:"varint,2,opt,name=on_recv_packet,json=onRecvPacket,proto3" json:"on_recv_packet,omitempty"`
	// on_acknowledgement counts the number of times OnAcknowledgement is called
	// in the underlying channel.
	OnAcknowledgement uint64 `protobuf:"varint,3,opt,name=on_acknowledgement,json=onAcknowledgement,proto3" json:"on_acknowledgement,omitempty"`
	// on_timeout counts the number of times OnTimeoutPacket is called in the
	// underlying channel.
	OnTimeout uint64 `protobuf:"varint,4,opt,name=on_timeout,json=onTimeout,proto3" json:"on_timeout,omitempty"`
	// send_packet counts the number of times SendPacket is called in the
	// underlying channel.
	SendPacket uint64 `protobuf:"varint,5,opt,name=send_packet,json=sendPacket,proto3" json:"send_packet,omitempty"`
	// channel_id defines the channel that is associated with the callback counts.
	ChannelId string `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *CallbackCounter) Reset()         { *m = CallbackCounter{} }
func (m *CallbackCounter) String() string { return proto.CompactTextString(m) }
func (*CallbackCounter) ProtoMessage()    {}
func (*CallbackCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d1cf6348eb2ada, []int{2}
}
func (m *CallbackCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CallbackCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CallbackCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CallbackCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCounter.Merge(m, src)
}
func (m *CallbackCounter) XXX_Size() int {
	return m.Size()
}
func (m *CallbackCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCounter.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCounter proto.InternalMessageInfo

func (m *CallbackCounter) GetOnChanOpen() uint64 {
	if m != nil {
		return m.OnChanOpen
	}
	return 0
}

func (m *CallbackCounter) GetOnRecvPacket() uint64 {
	if m != nil {
		return m.OnRecvPacket
	}
	return 0
}

func (m *CallbackCounter) GetOnAcknowledgement() uint64 {
	if m != nil {
		return m.OnAcknowledgement
	}
	return 0
}

func (m *CallbackCounter) GetOnTimeout() uint64 {
	if m != nil {
		return m.OnTimeout
	}
	return 0
}

func (m *CallbackCounter) GetSendPacket() uint64 {
	if m != nil {
		return m.SendPacket
	}
	return 0
}

func (m *CallbackCounter) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

// Counter defines a counter object.
// It is used only for genesis purposes. Collections does not need to use it.
type Counter struct {
	// count defines the count of the counter.
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// address defines the address that is associated with the count.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d1cf6348eb2ada, []int{3}
}
func (m *Counter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return m.Size()
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Counter) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// GenesisState is the state that must be provided at genesis.
type GenesisState struct {
	// counter defines the counter object.
	Counters []Counter `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters"`
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d1cf6348eb2ada, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetCounters() []Counter {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmosregistry.example.v1.Params")
	proto.RegisterType((*Metadata)(nil), "cosmosregistry.example.v1.Metadata")
	proto.RegisterType((*CallbackCounter)(nil), "cosmosregistry.example.v1.CallbackCounter")
	proto.RegisterType((*Counter)(nil), "cosmosregistry.example.v1.Counter")
	proto.RegisterType((*GenesisState)(nil), "cosmosregistry.example.v1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmosregistry/example/v1/types.proto", fileDescriptor_b9d1cf6348eb2ada)
}

var fileDescriptor_b9d1cf6348eb2ada = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0x8e, 0xdb, 0x34, 0x6d, 0x2e, 0xd1, 0xef, 0xa7, 0x58, 0x19, 0x4c, 0xa5, 0xb8, 0xa9, 0xf9,
	0xa3, 0xaa, 0x50, 0x5b, 0x0d, 0x5b, 0x98, 0x9a, 0x20, 0xa1, 0x0e, 0x88, 0xca, 0x45, 0x0c, 0x5d,
	0xac, 0x8b, 0xfd, 0xca, 0xb1, 0x62, 0xdf, 0x6b, 0xf9, 0x2e, 0x69, 0xfb, 0x15, 0x98, 0x18, 0xd8,
	0x59, 0x19, 0x3b, 0xf0, 0x21, 0x3a, 0x56, 0x4c, 0x4c, 0x08, 0x25, 0x43, 0xbf, 0x06, 0xf2, 0xdd,
	0xa5, 0x50, 0x44, 0x58, 0xac, 0xbb, 0xe7, 0x79, 0xee, 0x7d, 0x9f, 0xf7, 0xd1, 0x6b, 0xf2, 0x38,
	0x44, 0x9e, 0x21, 0x2f, 0x20, 0x4e, 0xb8, 0x28, 0x2e, 0x3d, 0xb8, 0xa0, 0x59, 0x9e, 0x82, 0x37,
	0x3b, 0xf4, 0xc4, 0x65, 0x0e, 0xdc, 0xcd, 0x0b, 0x14, 0x68, 0x3e, 0xb8, 0x2f, 0x73, 0xb5, 0xcc,
	0x9d, 0x1d, 0x6e, 0x6b, 0x2a, 0x90, 0x42, 0x4f, 0x5d, 0xd4, 0xab, 0xed, 0x76, 0x8c, 0x31, 0x2a,
	0xbc, 0x3c, 0x69, 0xb4, 0x45, 0xb3, 0x84, 0xa1, 0x27, 0xbf, 0x0a, 0x72, 0x9e, 0x91, 0xda, 0x09,
	0x2d, 0x68, 0xc6, 0xfb, 0xce, 0xfb, 0xdb, 0xab, 0xfd, 0xce, 0x0a, 0x53, 0x4a, 0xe3, 0x9c, 0x91,
	0xad, 0xd7, 0x20, 0x68, 0x44, 0x05, 0x35, 0x0f, 0x88, 0x99, 0x25, 0x51, 0x94, 0xc2, 0x39, 0x2d,
	0x20, 0x98, 0x41, 0xc1, 0x13, 0x64, 0x96, 0xd1, 0x35, 0xf6, 0xea, 0x7e, 0xeb, 0x17, 0xf3, 0x4e,
	0x11, 0xe6, 0x0e, 0x69, 0xd0, 0x3c, 0xbf, 0xd3, 0xad, 0x49, 0x1d, 0xa1, 0x79, 0xae, 0x05, 0xce,
	0xc7, 0x35, 0xf2, 0xff, 0x90, 0xa6, 0xe9, 0x88, 0x86, 0x93, 0x21, 0x4e, 0x99, 0x80, 0xc2, 0xec,
	0x92, 0x26, 0xb2, 0x20, 0x1c, 0x53, 0x16, 0x60, 0x0e, 0xaa, 0x7a, 0xd5, 0x27, 0xc8, 0x86, 0x63,
	0xca, 0xde, 0xe4, 0xc0, 0xcc, 0x47, 0xe4, 0x3f, 0x64, 0x41, 0x01, 0xe1, 0x2c, 0xc8, 0x69, 0x38,
	0x01, 0x21, 0x2b, 0x57, 0xfd, 0x26, 0x32, 0x1f, 0xc2, 0xd9, 0x89, 0xc4, 0x4a, 0xaf, 0xc8, 0x02,
	0x1a, 0x4e, 0x18, 0x9e, 0xa7, 0x10, 0xc5, 0x90, 0x01, 0x13, 0xd6, 0xba, 0x54, 0xb6, 0x90, 0x1d,
	0xdd, 0x27, 0xcc, 0x0e, 0x21, 0xc8, 0x02, 0x91, 0x64, 0x80, 0x53, 0x61, 0x55, 0xa5, 0xac, 0x8e,
	0xec, 0xad, 0x02, 0xca, 0x51, 0x38, 0xb0, 0x68, 0xd9, 0x70, 0x43, 0x99, 0x2a, 0x21, 0xdd, 0xae,
	0x43, 0x48, 0xe9, 0x99, 0x41, 0x1a, 0x24, 0x91, 0x55, 0x93, 0xa3, 0xd6, 0x35, 0x72, 0x1c, 0xf5,
	0x9f, 0x96, 0x49, 0x3f, 0x59, 0x91, 0xf4, 0x1f, 0x11, 0x38, 0x17, 0x64, 0x73, 0x99, 0x46, 0x9b,
	0x6c, 0x84, 0xe5, 0x51, 0xc7, 0xa0, 0x2e, 0x66, 0x8f, 0x6c, 0xd2, 0x28, 0x2a, 0x80, 0x73, 0x15,
	0xea, 0xc0, 0xfa, 0xfa, 0xe5, 0xa0, 0xad, 0xb7, 0xe1, 0x48, 0x31, 0xa7, 0xa2, 0x48, 0x58, 0xec,
	0x2f, 0x85, 0xfd, 0x87, 0xa5, 0x03, 0x7b, 0x95, 0x03, 0xdd, 0xf9, 0x93, 0x41, 0x9a, 0xaf, 0x80,
	0x01, 0x4f, 0xf8, 0xa9, 0xa0, 0x02, 0xcc, 0x63, 0xb2, 0x15, 0x2a, 0x8e, 0x5b, 0x46, 0x77, 0x7d,
	0xaf, 0xd1, 0x73, 0xdc, 0x95, 0xdb, 0xe9, 0xea, 0x32, 0x83, 0xfa, 0xf5, 0xf7, 0x9d, 0xca, 0xe7,
	0xdb, 0xab, 0x7d, 0xc3, 0xbf, 0x7b, 0x6e, 0xbe, 0x24, 0xb5, 0x5c, 0xae, 0x94, 0xf4, 0xdc, 0xe8,
	0xed, 0xfe, 0xa3, 0x90, 0xda, 0xbd, 0xdf, 0xeb, 0xe8, 0xb7, 0x83, 0x17, 0xd7, 0x73, 0xdb, 0xb8,
	0x99, 0xdb, 0xc6, 0x8f, 0xb9, 0x6d, 0x7c, 0x58, 0xd8, 0x95, 0x9b, 0x85, 0x5d, 0xf9, 0xb6, 0xb0,
	0x2b, 0x67, 0xbb, 0x71, 0x22, 0xc6, 0xd3, 0x91, 0x1b, 0x62, 0xe6, 0xfd, 0x7d, 0xcc, 0x51, 0x4d,
	0xfe, 0x00, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc7, 0x24, 0x10, 0x88, 0x03, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AppVersion) > 0 {
		i -= len(m.AppVersion)
		copy(dAtA[i:], m.AppVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AppVersion)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MiddlewareVersion) > 0 {
		i -= len(m.MiddlewareVersion)
		copy(dAtA[i:], m.MiddlewareVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MiddlewareVersion)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CallbackCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallbackCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CallbackCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x32
	}
	if m.SendPacket != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SendPacket))
		i--
		dAtA[i] = 0x28
	}
	if m.OnTimeout != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OnTimeout))
		i--
		dAtA[i] = 0x20
	}
	if m.OnAcknowledgement != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OnAcknowledgement))
		i--
		dAtA[i] = 0x18
	}
	if m.OnRecvPacket != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OnRecvPacket))
		i--
		dAtA[i] = 0x10
	}
	if m.OnChanOpen != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OnChanOpen))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Counter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Counter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Counter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Count != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Counters) > 0 {
		for iNdEx := len(m.Counters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Counters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MiddlewareVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.AppVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *CallbackCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OnChanOpen != 0 {
		n += 1 + sovTypes(uint64(m.OnChanOpen))
	}
	if m.OnRecvPacket != 0 {
		n += 1 + sovTypes(uint64(m.OnRecvPacket))
	}
	if m.OnAcknowledgement != 0 {
		n += 1 + sovTypes(uint64(m.OnAcknowledgement))
	}
	if m.OnTimeout != 0 {
		n += 1 + sovTypes(uint64(m.OnTimeout))
	}
	if m.SendPacket != 0 {
		n += 1 + sovTypes(uint64(m.SendPacket))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Counter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovTypes(uint64(m.Count))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Counters) > 0 {
		for _, e := range m.Counters {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MiddlewareVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MiddlewareVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallbackCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallbackCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallbackCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnChanOpen", wireType)
			}
			m.OnChanOpen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OnChanOpen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnRecvPacket", wireType)
			}
			m.OnRecvPacket = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OnRecvPacket |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnAcknowledgement", wireType)
			}
			m.OnAcknowledgement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OnAcknowledgement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnTimeout", wireType)
			}
			m.OnTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OnTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendPacket", wireType)
			}
			m.SendPacket = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendPacket |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Counter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Counter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Counter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Counters = append(m.Counters, Counter{})
			if err := m.Counters[len(m.Counters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
